### ISSUE TITLE
Make errors more verbose?

### ISSUE THREAD

**Issue by jcayzac** [tibdex/github-app-token#2]
Hi,

I just configured an organization app and setup this action. My workflow fails with the message below:

```
Run tibdex/github-app-token@v1
  with:
    app_id: ***
    private_key: ***
##[error]Not Found
```

The string `Not Found` [doesn't seem to even appear in this repo](https://github.com/tibdex/github-app-token/search?q=Not+Found&type=Code), so I don't have any other option but go create a personal token instead. A more verbose error would have helped.

**Comment by abatilo** [comment]
This error was happening to me because I had created a GitHub App, but I didn't actually install the app to the repository/organization. So there was an `Not found` error being thrown due to the call to [getRepoInstallation](https://github.com/tibdex/github-app-token/blob/master/src/index.ts#L18) getting a 404 since there isn't a repo installation.
