### ISSUE TITLE
private_key input should be in the secrets

### ISSUE THREAD

**Issue by spender0** [tibdex/github-app-token#38]
according to https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow private_key should be in secrets

If I put the action into my reusable workflow GitHub automatically removes private_key input and I get the error:

```
Run tibdex/github-app-token@v1.5.2
  with:
    app_id: my app id
    installation_id: my id 
    repository: my repo name
 
Error: Error: Input required and not supplied: private_key
```

**Comment by tibdex** [comment]
> private_key should be in secrets

Where? 

- Not in `action.yml` because `secret` is not part of the [metadata syntax for actions](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions).
- Not in `README.md` because the workflow shown there is not meant to be reusable: it's only an example.

If you define your own reusable workflows then yes you could use the `secrets` keyword in your `workflow_call`.

**Comment by spender0** [comment]
> 

Hi, yes, you are right!
Then I don't know how to fix the problem, if I put this action into a reusable workflow the private_key seems to be removed automatically. Probably, because it is not safe to pass a secret via inputs.

**Comment by kkdrz** [comment]
@spender0 if what you're saying is true, then below may be a workaround:

```
uses: my-reusable-workflows/.github/workflows/my-workflow.yml@main
secrets: inherit
```
?
