### ISSUE TITLE
Please use environment files instead of set-output

### ISSUE THREAD

**Issue by creachadair** [tibdex/github-app-token#69]
Per [the GitHub blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), using `set-output` to define action outputs is deprecated in favour of using [environment files](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files). It looks like this action still uses `set-output`, which results in warnings being posted in the workflow output.

Please consider updating the action to use environment files instead? I would ordinarily send a PR, but the action source appears to be compiled from somewhere else, so I assume you'd prefer me not to edit it as-committed. (If that's wrong, and you can point me to where the change should be made, I'm happy to follow up with a PR).

**Comment by tibdex** [comment]
You're probably using an old version of this action since the latest one depends on:

https://github.com/tibdex/github-app-token/blob/c2055a00597a80f713b78b1650e8d3418f4d9a65/package.json#L17

which is [OK according to the GitHub blog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#patching-your-actions-and-workflows):

> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

**Comment by creachadair** [comment]
Ah, my apologies, it looks like that is correct. I grepped the source at the tip of main and it looks like it is still calling out to `set-output`, but perhaps that is a false positive.
